### ISSUE TITLE
Loading idasec.py with an error: " QWidget: Must construct a QApplication before a QWidget"

### ISSUE THREAD

**Issue by APlus123** [RobinDavid/idasec#5]
Hi,Robin

     So sorry to trouble you ，while I successfully installed BINSEC_V0.2, SIP  and PyQt5 ,then ran "binsec server /home/dr0ic1er/Desktop/T4.so" , and loaded the idasec.py script in IDA , the IDA crashed with an error: " QWidget: Must construct a QApplication before a QWidget Aborted (core dumped). "

     This may be the problem that QApplication wasn't initialized. I also wrote a PyQt5 python script, but IDA loaded the ui  properly, the code likes this:
++++++++++++++++++++++++++++++++++++++++
`from PyQt5 import QtWidgets

class myWindow(QtWidgets.QWidget):

     def __init__(self):

         super(myWindow,self).__init__()

import sys
app = QtWidgets.QApplication(sys.argv)
windows=myWindow()
windows.show()
sys.exit(app.exec_())
`
++++++++++++++++++++++++++++++++++++++
so I just wonder whether  compiling the Qt source code in debug mode can solve this problem  ? 

Following is my expirement environment:
OS: Ubuntu 16.04.02 LTS 64-bits
cmake version 3.5.1
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
protobuf-2.6.1
ZeroMQ v4.2.5
lzmq v0.4.4

Qt5.5.1 with QMake version 3.0 ,which installed by the Qt prebuild binary -- qt-unified-linux-x86-2.0.5-2-online.run
SIP 4.19.8
PyQt5

     Look forward to your reply with best wishes !
     Regards,
     APlus123

**Comment by techbliss** [comment]
Since ida is allready QT,  you cant load app twize.

this line should be deleted.

`app = QtWidgets.QApplication(sys.argv)`
and this line `

should be replaced with
`sys.exit(app.exec_())`
`app.exec_()`

When using those lines , it is like you load main ida(exe) twice, there for don't use it when using python either .
PyQt calls the main c++ QT, so basically just callbacks, so you trying to load QApplication twize.

Ot use workaround like this.
[Example](https://github.com/techbliss/ADB_Helper_QT_Super_version/blob/master/QtApps/SuperADB/ADB_QT.py#L628l)

**Comment by APlus123** [comment]
Hi, @techbliss :
      Much appreciated to your great reply, no matter use `app.exec_()`  or `sys.exit(app.exec_())`, the follwing script (a test case wrote by me)all successfully loaded in IDA.
++++++++++++++++++++++++++++++++++++++++
from PyQt5 import QtWidgets

class myWindow(QtWidgets.QWidget):
   def __init__(self):
       super(myWindow,self).__init__()

if __name__ == "__main__":
  import sys
  app = QtWidgets.QApplication(sys.argv)
  windows=myWindow()
  windows.show()
  sys.exit(app.exec_())
++++++++++++++++++++++++++++++++++++++

      Which really confused me is  that the script idasec.py[https://github.com/RobinDavid/idasec/blob/master/idasec.py#L281l] (url)in idasec folder. When I loade the idasec.py script in IDA , the IDA crashed with an error: " QWidget: Must construct a QApplication before a QWidget Aborted (core dumped). "
       Regards,
       APlus123

**Comment by APlus123** [comment]
Hi, @techbliss :
Much appreciated to your great reply, no matter use app.exec_() or sys.exit(app.exec_()), the follwing script (a test case wrote by me)all successfully loaded in IDA.
++++++++++++++++++++++++++++++++++++++++
from PyQt5 import QtWidgets

class myWindow(QtWidgets.QWidget):
def init(self):
super(myWindow,self).init()

if name == "main":
import sys
app = QtWidgets.QApplication(sys.argv)
windows=myWindow()
windows.show()
sys.exit(app.exec_())
++++++++++++++++++++++++++++++++++++++

  Which really confused me is  that the script [idasec.py] (https://github.com/RobinDavid/idasec/blob/master/idasec.py#L281l)in idasec folder. When I loade the idasec.py script in IDA , the IDA crashed with an error: " QWidget: Must construct a QApplication before a QWidget Aborted (core dumped). "
   Regards,
   APlus123

**Comment by APlus123** [comment]
Hi, @techbliss :
Much appreciated to your great reply, no matter use app.exec_() or sys.exit(app.exec_()), the follwing script (a test case wrote by me)all successfully loaded in IDA.
++++++++++++++++++++++++++++++++++++++++
from PyQt5 import QtWidgets

class myWindow(QtWidgets.QWidget):
def init(self):
super(myWindow,self).init()

if name == "main":
import sys
app = QtWidgets.QApplication(sys.argv)
windows=myWindow()
windows.show()
sys.exit(app.exec_())
++++++++++++++++++++++++++++++++++++++

Which really confused me is that the script [https://github.com/RobinDavid/idasec/blob/master/idasec.py#L281l](idasec.py) in idasec folder. When I loade the idasec.py script in IDA , the IDA crashed with an error: " QWidget: Must construct a QApplication before a QWidget Aborted (core dumped). "

Regards,
APlus123

**Comment by APlus123** [comment]
Hi, @techbliss :
Much appreciated to your great reply, no matter use app.exec_() or sys.exit(app.exec_()), the follwing script (a test case wrote by me)all successfully loaded in IDA.
++++++++++++++++++++++++++++++++++++++++
from PyQt5 import QtWidgets

class myWindow(QtWidgets.QWidget):
def init(self):
super(myWindow,self).init()

if name == "main":
import sys
app = QtWidgets.QApplication(sys.argv)
windows=myWindow()
windows.show()
sys.exit(app.exec_())
++++++++++++++++++++++++++++++++++++++

Which really confused me is that the script l in the project [idasec](https://github.com/RobinDavid/idasec) .When I loaded the script [idasec.py](https://github.com/RobinDavid/idasec/blob/master/idasec.py#L281) in IDA , the IDA crashed with an error: " QWidget: Must construct a QApplication before a QWidget Aborted (core dumped). "

Regards,
APlus123

**Comment by RobinDavid** [comment]
Hi @APlus123 . Did it solved your problem ? By the way which version of IDA are you using ?

Please note that I stopped working on this plugin.

**Comment by APlus123** [comment]
Hi @RobinDavid ：
     So honored to hear from you. After I installed all the dependencies ,it also occus the problem. The IDA I use is IDA_Pro_v6.4_(Linux)

**Comment by APlus123** [comment]
Hi @RobinDavid ：
So honored to hear from you. After I installed all the dependencies ,it also occurs the problem. The IDA I using is IDA_Pro_v6.4_(Linux),following is the detail:
---------------------------------------------------------------------------------------------
Python 2.7.2 (default, Mar 26 2012, 16:13:09) -----while on my local machine I installed python2.7.15 -32bit to /usr/local ,in case of (by compiling source code), in case of 
[GCC 4.2.4 (Ubuntu 4.2.4-1ubuntu4)] 
IDAPython 64-bit v1.5.6 final (serial 0) (c) The IDAPython Team <idapython@googlegroups.com>
---------------------------------------------------------------------------------------------
I just follow your steps and enviroment in the video on [youtube](https://youtu.be/Z14ab_rzjfA), the difference is that IDASEC works perfectly on your machine , so I just don't know where is wrong?
In addition, considering the compatibility, my sip.so and PyQt5 are all 32-bits,although my PC is ubuntu 16.04LTS amd64.

On my machine the Qt version is Qt5.5.1 with QMake version 3.0 ,which installed by the Qt prebuild binary -- [ qt-unified-linux-x86-2.0.5-2-online.run ]. I didn't compile the Qt source code.

So, I just wonder whether compiling the Qt source code in debug mode can solve this problem ?

So sorry to trouble you ,and thanks again!
APlus123

**Comment by APlus123** [comment]
Hi @RobinDavid ：
So honored to hear from you. After I installed all the dependencies ,it also occurs the problem. The IDA I using is IDA_Pro_v6.4_(Linux),following is the detail:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Python 2.7.2 (default, Mar 26 2012, 16:13:09) -----while on my local machine I installed python2.7.15 -32bit to /usr/local ,in case of (by compiling source code), in case of
[GCC 4.2.4 (Ubuntu 4.2.4-1ubuntu4)]
IDAPython 64-bit v1.5.6 final (serial 0) (c) The IDAPython Team idapython@googlegroups.com
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

I just follow your steps and enviroment in the video on youtube, the difference is that IDASEC works perfectly on your machine , so I just don't know where is wrong?
In addition, considering the compatibility, my sip.so and PyQt5 are all 32-bits,although my PC is ubuntu 16.04LTS amd64.

On my machine the Qt version is Qt5.5.1 with QMake version 3.0 ,which installed by the Qt prebuild binary -- [ qt-unified-linux-x86-2.0.5-2-online.run ]. I didn't compile the Qt source code.

So, I just wonder whether compiling the Qt source code in debug mode can solve this problem ?

So sorry to trouble you ,and thanks again!
APlus123

**Comment by APlus123** [comment]
Hi @RobinDavid ：
So honored to hear from you. After I installed all the dependencies ,it also occurs the problem. The IDA I using is IDA_Pro_v6.4_(Linux),following is the detail:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Python 2.7.2 (default, Mar 26 2012, 16:13:09) -----while on my local machine I installed python2.7.15 -32bit to /usr/local ,in case of (by compiling source code), in case of
[GCC 4.2.4 (Ubuntu 4.2.4-1ubuntu4)]
IDAPython 64-bit v1.5.6 final (serial 0) (c) The IDAPython Team idapython@googlegroups.com
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

I just follow your steps and enviroment in the video [youtube](https://youtu.be/Z14ab_rzjfA) , the difference is that IDASEC works perfectly on your machine , so I just don't know where is wrong?
In addition, considering the compatibility, my sip.so and PyQt5 are all 32-bits,although my PC is ubuntu 16.04LTS amd64.

On my machine the Qt version is Qt5.5.1 with QMake version 3.0 ,which installed by the Qt prebuild binary -- [ qt-unified-linux-x86-2.0.5-2-online.run ]. I didn't compile the Qt source code.

So, I just wonder whether compiling the Qt source code in debug mode can solve this problem ?

So sorry to trouble you ,and thanks again!
APlus123

**Comment by APlus123** [comment]
Hi @RobinDavid ：
So honored to hear from you. After I installed all the dependencies ,it also occurs the problem. The IDA I using is IDA_Pro_v6.4_(Linux),following is the detail:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Python 2.7.2 (default, Mar 26 2012, 16:13:09) -----while on my local machine I installed python2.7.15 -32bit to /usr/local  (by compiling source code), in case of PyUnicodeUCS4_DecodeUTF8 error.
[GCC 4.2.4 (Ubuntu 4.2.4-1ubuntu4)]
IDAPython 64-bit v1.5.6 final (serial 0) (c) The IDAPython Team idapython@googlegroups.com
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

I just follow your steps and enviroment in the video youtube , the difference is that IDASEC works perfectly on your machine , so I just don't know where is wrong?
In addition, considering the compatibility, my sip.so and PyQt5 are all 32-bits,although my PC is ubuntu 16.04LTS amd64.

On my machine the Qt version is Qt5.5.1 with QMake version 3.0 ,which installed by the Qt prebuild binary -- [ qt-unified-linux-x86-2.0.5-2-online.run ]. I didn't compile the Qt source code.

So, I just wonder whether compiling the Qt source code in debug mode can solve this problem ?

So sorry to trouble you ,and thanks again!
APlus123

**Comment by APlus123** [comment]
Hi @RobinDavid ：
So honored to hear from you. After I installed all the dependencies ,it also occurs the problem. The IDA I using is IDA_Pro_v6.4_(Linux),following is the detail:
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
Python 2.7.2 (default, Mar 26 2012, 16:13:09) -----while on my local machine I installed python2.7.15 -32bit to /usr/local (by compiling source code), in case of PyUnicodeUCS4_DecodeUTF8 error.
[GCC 4.2.4 (Ubuntu 4.2.4-1ubuntu4)]
IDAPython 64-bit v1.5.6 final (serial 0) (c) The IDAPython Team idapython@googlegroups.com
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

I just follow your steps and enviroment in [youtube video ](https://youtu.be/Z14ab_rzjfA)  , the difference is that IDASEC works perfectly on your machine , so I just don't know where is wrong?
In addition, considering the compatibility, my sip.so and PyQt5 are all 32-bits,although my PC is ubuntu 16.04LTS amd64.

On my machine the Qt version is Qt5.5.1 with QMake version 3.0 ,which installed by the Qt prebuild binary -- [ qt-unified-linux-x86-2.0.5-2-online.run ]. I didn't compile the Qt source code.

So, I just wonder whether compiling the Qt source code in debug mode can solve this problem ?

So sorry to trouble you ,and thanks again!
APlus123

**Comment by RobinDavid** [comment]
No I really don't think that compiling the Qt source code in debug would help.

I have a question, are you using the python 2.7 of the system or the one provided by IDA ?

I remember that using the python of the system does not work and when installing IDA you should choose to use the one provided by IDA. That implies to install all the dependencies in the ida-6.4/python folder.

Another point is that I updated idasec to work with ida-7.0 and I am not sure it is still backward compatible. Thus it might be a good idea to check a previous version of it like this one: 6f4d9acc57452ac3e10dfd09dc97fcdcf34660bc

**Comment by APlus123** [comment]
Hi @RobinDavid :
Yeah, using the python of the system will prompt lack of dependencies of IDA.  

My IDA is green unzipped version, not the installation package version(no installation package version on Internet), So I just using the python of the system(in /usr/local directory) to install all dependencies, and then copy all needed dependencies to IDA_6.4_Pro/python directory. Although IDA don't prompt lack of dependencies,it may have some influence.

I'll try to install IDA by source later, and then give you the feedback.

Much appreciated to your kind help,and thanks again!

Regards,
APlus123

**Comment by APlus123** [comment]
Hi @RobinDavid :
After I installed all dependencies in the ida-6.4/python folder, the error occured as same. Debug step by step, I finally find IDA crashed at [idasec.py](https://github.com/RobinDavid/idasec/blob/master/idasec.py#L39l)  `from idasec.analysis.generic_analysis import GenericAnalysis` . 

Starting from line 39(idasec.py)，the follwing lines all made IDA a crash, " QWidget: Must construct a QApplication before a QWidget".

Following is environmental variable of my IDA. 
______________________________________________________________________________________________________
Python>sys.path
['/home/dr0ic1er/IDA_Pro_v6.4/python/lib/python27.zip', '/home/dr0ic1er/IDA_Pro_v6.4/python/lib/python2.7/', '/home/dr0ic1er/IDA_Pro_v6.4/python/lib/python2.7/plat-linux2', '/home/dr0ic1er/IDA_Pro_v6.4/python/lib/python2.7/lib-tk', '/home/dr0ic1er/IDA_Pro_v6.4/python/lib/python2.7/lib-old', '/home/dr0ic1er/IDA_Pro_v6.4/python/lib/python2.7/lib-dynload', '/home/dr0ic1er/IDA_Pro_v6.4/python', '/home/dr0ic1er']
______________________________________________________________________________________________________

So sorry to trouble you ,and much appreciated to your kind help !
APlus123

**Comment by RobinDavid** [comment]
For the record. The issue arises when launching ``idat`` which indeed does not start the Qt ``QApplication``. Thus the import of the plugin raises an issue as it tries creating widget. Here is a small file to call **AAAAAA.py** and to put in plugins:

```python
import os
import psutil

from PyQt5.QtWidgets import QApplication, QWidget

if psutil.Process(os.getpid()).name() == "idat64":
    print("launch the app")
    app = QApplication(sys.argv)
```

**Comment by APlus123** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的邮件我已收到，我将尽快回复您，谢谢！
